In [ ]:
import numpy as np

# Part 1: Creating ndarrays

1. Convert the below given list of strings to an int32 NumPy array

In [ ]:
slist = ['2.5', '1.25', '0.024','2.999','1024.5']

In [ ]:
# Write your code here
new_list = np.array(slist)
new_array = new_list.astype(float)
new_array

array([2.5000e+00, 1.2500e+00, 2.4000e-02, 2.9990e+00, 1.0245e+03])

2. Create an empty 5x5 NumPy matrix

In [ ]:
# Write your code here
matrix = np.empty((5,5), dtype=int)
matrix

array([[94733224018880,              0,              0,              0,
                     0],
       [             0,              0,              0,              0,
                     0],
       [             0,              0,              0,              0,
                     0],
       [             0,              0,              0,              0,
                     0],
       [             0,              0,              0,              0,
                     0]])

# Part 2: Operations between Arrays and Scalars

3. Create a 1x7 Numpy array whose elements consist of a geometric progression with a = 1 & r = 3, terms are arranged indexwise, for ex

In [ ]:
sample_output = [1,3,9,27,81]

In [ ]:
# Write your code here
np.geomspace(1, 729, num=7, dtype=int)

array([  1,   3,   9,  27,  81, 242, 729])

4. Transform each of the element of the below matrix according to the below equation

    if x is an elements in input matrix, output matrix should have 
$1/(x^2 + 1)$ in its place



In [ ]:
mat = [[1,2,3],[4,5,6]]

In [ ]:
row = len(mat)
col = len(mat[0])

for i in range(row):
  for j in range(col):
    mat[i][j] = 1/(mat[i][j]*mat[i][j] + 1)

# Part 3: Basic Indexing and Slicing

5. Make a 5x5 NumPy array of all zeros and use indexing and broadcasting to modify it such that all the elements not on the border are 1, for example

In [ ]:
output_sample = np.array([[0,0,0,0,0],[0,1,1,1,0],[0,1,1,1,0],[0,1,1,1,0],[0,0,0,0,0]])
output_sample

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
#write your code here
matrix = np.zeros((5,5))
matrix[1:4,1:4] = 1
matrix

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

6. Given the 3x3x3, 3-dimensional NumPy array

In [ ]:
arr = np.arange(27).reshape((3,3,3))
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

i. Slice this matrix to contain only second and third rows, first and second columns of the given matrix.

In [ ]:
sample_output = np.array([[[3,4],[6,7]],[[12,13],[15,16]],[[21,22],[24,25]]])
sample_output

array([[[ 3,  4],
        [ 6,  7]],

       [[12, 13],
        [15, 16]],

       [[21, 22],
        [24, 25]]])

In [ ]:
#write your code here
ans = arr[0:,1:,0:2]
ans

array([[[ 3,  4],
        [ 6,  7]],

       [[12, 13],
        [15, 16]],

       [[21, 22],
        [24, 25]]])

ii. Output a two dimensional matrix as shown below

In [ ]:
sample_output = np.array([[0,3,6],[9,12,15],[18,21,14]])
sample_output

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 14]])

In [ ]:
#write your code here
sample_output

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 14]])

# Part 4: Boolean Indexing

7. Given the following array, modify it such that even values stay the same and output contains 0s instead of odd values

In [ ]:
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
sample_output = np.array([[0,0,2],[0,4,0],[6,0,8]])
sample_output

array([[0, 0, 2],
       [0, 4, 0],
       [6, 0, 8]])

In [ ]:
arr[arr % 2 == 1] = 0
arr

array([[0, 0, 2],
       [0, 4, 0],
       [6, 0, 8]])

# Part 5: Fancy Indexing

8. For the given matrix, use fancy indexing to output a 2d matrix consisting all the even elements of the given matrix

In [ ]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [ ]:
sample_output = np.array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22],
       [24, 26],
       [28, 30]])
sample_output

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22],
       [24, 26],
       [28, 30]])

In [ ]:
# Write your code here
cols = len(arr[0])
arr[0:,0:cols:2]


array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22],
       [24, 26],
       [28, 30]])

# Part 6: Expressing Conditional Logic as Array Operations



Given two following matrices, use conditional logic to replace all the odd elements of matrix A with even elements of matrix B

In [ ]:
A = np.arange(9).reshape((3,3))
B = np.arange(1,10).reshape((3,3))
print(A)
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
sample_output = np.array([[0, 2, 2],
       [4, 4, 6],
       [6, 8, 8]])
sample_output

array([[0, 2, 2],
       [4, 4, 6],
       [6, 8, 8]])

In [ ]:
# Write your code here
A[A % 2 == 1] = B[A % 2 == 1]
A

array([[0, 2, 2],
       [4, 4, 6],
       [6, 8, 8]])

# Part 7: Linear Algebra

Given the following system of equations, solve for x and y using either `numpy.linalg.solve(m1,m2)` or using `inv` and `dot`

2x + 5y = 20

3x + 6y = 12

In [ ]:
m_list = [[2, 5], [3, 6]]
A = np.array(m_list)

inv_A = np.linalg.inv(A)

B = np.array([20, 12])
X = np.linalg.inv(A).dot(B)

X

array([-20.,  12.])